# Generated by Django 5.2 on 2025-04-18 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentoVectorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('vector', models.JSONField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.archivo')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tema')),
            ],
        ),
    ]
