# Generated by Django 5.2 on 2025-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_fragmentovectorizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
