# Generated by Django 5.2 on 2025-04-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_conversacion_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='id_conversacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
